import 'package:flutter/material.dart';

// GENERATED by tool/fitgen.py — edit the spec there and re-run, don't hand-edit.
// The Dart table and both l10n dictionaries come out of one spec, which is what
// makes a missing translation impossible rather than merely unlikely.

/// Which built-in motion loop (see lib/widgets/exercise_motion.dart) plays
/// behind an exercise's icon — a lightweight, zero-asset stand-in for a real
/// form-demo GIF/video (deliberately not that: no external hosting/CDN, see
/// the architecture note in exercise_motion.dart).
enum ExerciseMotion { squat, pushup, lunge, plank, jump, core }

/// Who a routine is aimed at. `both` appears under either tab instead of being
/// duplicated per gender — a squat is a squat.
enum FitGender { male, female, both }

enum FitLevel { beginner, intermediate, advanced }

/// What you need to hand. Drives the equipment chip and the
/// "no equipment only" filter.
enum FitEquipment { none, dumbbells, barbell, bar }

/// One exercise: name + short technique cue read aloud by the on-device TTS
/// coach, both stored as l10n KEYS (not literal text) so the exercise DB
/// follows the app's language setting — resolve with `context.t(nameKey)` /
/// `context.t(cueKey)` at the point of use.
class FitExercise {
  final String id;
  final String nameKey;
  final String cueKey;
  final IconData icon;
  final ExerciseMotion motion;
  const FitExercise(this.id, this.nameKey, this.cueKey, this.icon, this.motion);
}

/// A timed circuit: work/rest seconds apply to every exercise in it, and the
/// whole circuit repeats [sets] times.
///
/// Duration, exercise count and calories are all COMPUTED from these numbers
/// rather than stored as text, so a card can never drift out of sync with the
/// workout it describes.
class FitRoutine {
  final String id;
  final String titleKey;
  final IconData icon;
  final int workSec;
  final int restSec;
  final int sets;
  final FitGender gender;
  final FitLevel level;
  final FitEquipment equipment;

  /// Rough intensity for the calorie estimate. Per-minute on purpose: a stored
  /// total would stop matching as soon as [sets] changed.
  final int kcalPerMin;

  final List<FitExercise> exercises;

  const FitRoutine(
    this.id,
    this.titleKey,
    this.icon,
    this.workSec,
    this.restSec, {
    this.sets = 1,
    this.gender = FitGender.both,
    this.level = FitLevel.beginner,
    this.equipment = FitEquipment.none,
    this.kcalPerMin = 6,
    required this.exercises,
  });

  int get estimatedMinutes =>
      (((workSec + restSec) * exercises.length * sets) / 60)
          .round()
          .clamp(1, 999);

  int get estimatedKcal => estimatedMinutes * kcalPerMin;

  String get levelKey => 'fitLevel_${level.name}';
  String get equipmentKey => 'fitEquip_${equipment.name}';

  bool matchesGender(FitGender tab) =>
      gender == FitGender.both || gender == tab;
}

// ─── Exercise library ───────────────────────────────────────────────────────
const _squat = FitExercise('squat', 'exSquatName', 'exSquatCue',
    Icons.accessibility_new_rounded, ExerciseMotion.squat);
const _pushup = FitExercise('pushup', 'exPushupName', 'exPushupCue',
    Icons.fitness_center_rounded, ExerciseMotion.pushup);
const _lunge = FitExercise('lunge', 'exLungeName', 'exLungeCue',
    Icons.directions_walk_rounded, ExerciseMotion.lunge);
const _plank = FitExercise('plank', 'exPlankName', 'exPlankCue',
    Icons.horizontal_rule_rounded, ExerciseMotion.plank);
const _mountainClimber = FitExercise('mountain_climber', 'exMountainClimberName', 'exMountainClimberCue',
    Icons.terrain_rounded, ExerciseMotion.core);
const _gluteBridge = FitExercise('glute_bridge', 'exGluteBridgeName', 'exGluteBridgeCue',
    Icons.self_improvement_rounded, ExerciseMotion.squat);
const _jumpInPlace = FitExercise('jump_in_place', 'exJumpInPlaceName', 'exJumpInPlaceCue',
    Icons.directions_run_rounded, ExerciseMotion.jump);
const _sumoSquat = FitExercise('sumo_squat', 'exSumoSquatName', 'exSumoSquatCue',
    Icons.accessibility_new_rounded, ExerciseMotion.squat);
const _reverseLunge = FitExercise('reverse_lunge', 'exReverseLungeName', 'exReverseLungeCue',
    Icons.directions_walk_rounded, ExerciseMotion.lunge);
const _jumpingJack = FitExercise('jumping_jack', 'exJumpingJackName', 'exJumpingJackCue',
    Icons.accessibility_rounded, ExerciseMotion.jump);
const _highKnees = FitExercise('high_knees', 'exHighKneesName', 'exHighKneesCue',
    Icons.directions_run_rounded, ExerciseMotion.jump);
const _burpee = FitExercise('burpee', 'exBurpeeName', 'exBurpeeCue',
    Icons.whatshot_rounded, ExerciseMotion.jump);
const _jumpSquat = FitExercise('jump_squat', 'exJumpSquatName', 'exJumpSquatCue',
    Icons.arrow_upward_rounded, ExerciseMotion.jump);
const _highKneeMarch = FitExercise('high_knee_march', 'exHighKneeMarchName', 'exHighKneeMarchCue',
    Icons.directions_walk_rounded, ExerciseMotion.jump);
const _skaterJump = FitExercise('skater_jump', 'exSkaterJumpName', 'exSkaterJumpCue',
    Icons.swap_horiz_rounded, ExerciseMotion.jump);
const _sideShuffle = FitExercise('side_shuffle', 'exSideShuffleName', 'exSideShuffleCue',
    Icons.compare_arrows_rounded, ExerciseMotion.lunge);
const _crunches = FitExercise('crunches', 'exCrunchesName', 'exCrunchesCue',
    Icons.rotate_right_rounded, ExerciseMotion.core);
const _bicycle = FitExercise('bicycle', 'exBicycleName', 'exBicycleCue',
    Icons.pedal_bike_rounded, ExerciseMotion.core);
const _legRaise = FitExercise('leg_raise', 'exLegRaiseName', 'exLegRaiseCue',
    Icons.height_rounded, ExerciseMotion.core);
const _sidePlank = FitExercise('side_plank', 'exSidePlankName', 'exSidePlankCue',
    Icons.swap_horiz_rounded, ExerciseMotion.plank);
const _superman = FitExercise('superman', 'exSupermanName', 'exSupermanCue',
    Icons.airline_seat_flat_rounded, ExerciseMotion.core);
const _russianTwist = FitExercise('russian_twist', 'exRussianTwistName', 'exRussianTwistCue',
    Icons.sync_alt_rounded, ExerciseMotion.core);
const _flutterKicks = FitExercise('flutter_kicks', 'exFlutterKicksName', 'exFlutterKicksCue',
    Icons.waves_rounded, ExerciseMotion.core);
const _kneePushup = FitExercise('knee_pushup', 'exKneePushupName', 'exKneePushupCue',
    Icons.fitness_center_rounded, ExerciseMotion.pushup);
const _inclinePushup = FitExercise('incline_pushup', 'exInclinePushupName', 'exInclinePushupCue',
    Icons.stairs_rounded, ExerciseMotion.pushup);
const _declinePushup = FitExercise('decline_pushup', 'exDeclinePushupName', 'exDeclinePushupCue',
    Icons.north_rounded, ExerciseMotion.pushup);
const _widePushup = FitExercise('wide_pushup', 'exWidePushupName', 'exWidePushupCue',
    Icons.open_with_rounded, ExerciseMotion.pushup);
const _diamondPushup = FitExercise('diamond_pushup', 'exDiamondPushupName', 'exDiamondPushupCue',
    Icons.change_history_rounded, ExerciseMotion.pushup);
const _pushupHold = FitExercise('pushup_hold', 'exPushupHoldName', 'exPushupHoldCue',
    Icons.timer_rounded, ExerciseMotion.plank);
const _chestFlyDumbbell = FitExercise('chest_fly_dumbbell', 'exChestFlyDumbbellName', 'exChestFlyDumbbellCue',
    Icons.fitness_center_rounded, ExerciseMotion.pushup);
const _benchPressBarbell = FitExercise('bench_press_barbell', 'exBenchPressBarbellName', 'exBenchPressBarbellCue',
    Icons.monitor_weight_rounded, ExerciseMotion.pushup);
const _tricepsDip = FitExercise('triceps_dip', 'exTricepsDipName', 'exTricepsDipCue',
    Icons.chair_rounded, ExerciseMotion.pushup);
const _bicepsCurl = FitExercise('biceps_curl', 'exBicepsCurlName', 'exBicepsCurlCue',
    Icons.fitness_center_rounded, ExerciseMotion.pushup);
const _hammerCurl = FitExercise('hammer_curl', 'exHammerCurlName', 'exHammerCurlCue',
    Icons.fitness_center_rounded, ExerciseMotion.pushup);
const _tricepsExtension = FitExercise('triceps_extension', 'exTricepsExtensionName', 'exTricepsExtensionCue',
    Icons.vertical_align_top_rounded, ExerciseMotion.pushup);
const _armCircles = FitExercise('arm_circles', 'exArmCirclesName', 'exArmCirclesCue',
    Icons.autorenew_rounded, ExerciseMotion.jump);
const _pikePushup = FitExercise('pike_pushup', 'exPikePushupName', 'exPikePushupCue',
    Icons.change_history_rounded, ExerciseMotion.pushup);
const _shoulderTap = FitExercise('shoulder_tap', 'exShoulderTapName', 'exShoulderTapCue',
    Icons.pan_tool_rounded, ExerciseMotion.plank);
const _lateralRaise = FitExercise('lateral_raise', 'exLateralRaiseName', 'exLateralRaiseCue',
    Icons.open_with_rounded, ExerciseMotion.pushup);
const _frontRaise = FitExercise('front_raise', 'exFrontRaiseName', 'exFrontRaiseCue',
    Icons.north_rounded, ExerciseMotion.pushup);
const _overheadPress = FitExercise('overhead_press', 'exOverheadPressName', 'exOverheadPressCue',
    Icons.vertical_align_top_rounded, ExerciseMotion.pushup);
const _birdDog = FitExercise('bird_dog', 'exBirdDogName', 'exBirdDogCue',
    Icons.all_inclusive_rounded, ExerciseMotion.core);
const _reverseSnowAngel = FitExercise('reverse_snow_angel', 'exReverseSnowAngelName', 'exReverseSnowAngelCue',
    Icons.blur_on_rounded, ExerciseMotion.core);
const _pullUp = FitExercise('pull_up', 'exPullUpName', 'exPullUpCue',
    Icons.fitness_center_rounded, ExerciseMotion.pushup);
const _chinUp = FitExercise('chin_up', 'exChinUpName', 'exChinUpCue',
    Icons.fitness_center_rounded, ExerciseMotion.pushup);
const _australianPullup = FitExercise('australian_pullup', 'exAustralianPullupName', 'exAustralianPullupCue',
    Icons.horizontal_rule_rounded, ExerciseMotion.pushup);
const _dumbbellRow = FitExercise('dumbbell_row', 'exDumbbellRowName', 'exDumbbellRowCue',
    Icons.rowing_rounded, ExerciseMotion.pushup);
const _goodMorning = FitExercise('good_morning', 'exGoodMorningName', 'exGoodMorningCue',
    Icons.south_rounded, ExerciseMotion.squat);
const _wallSit = FitExercise('wall_sit', 'exWallSitName', 'exWallSitCue',
    Icons.crop_square_rounded, ExerciseMotion.plank);
const _bulgarianSplitSquat = FitExercise('bulgarian_split_squat', 'exBulgarianSplitSquatName', 'exBulgarianSplitSquatCue',
    Icons.stairs_rounded, ExerciseMotion.lunge);
const _stepUp = FitExercise('step_up', 'exStepUpName', 'exStepUpCue',
    Icons.stairs_rounded, ExerciseMotion.lunge);
const _calfRaise = FitExercise('calf_raise', 'exCalfRaiseName', 'exCalfRaiseCue',
    Icons.keyboard_double_arrow_up_rounded, ExerciseMotion.squat);
const _gobletSquat = FitExercise('goblet_squat', 'exGobletSquatName', 'exGobletSquatCue',
    Icons.monitor_weight_rounded, ExerciseMotion.squat);
const _barbellSquat = FitExercise('barbell_squat', 'exBarbellSquatName', 'exBarbellSquatCue',
    Icons.monitor_weight_rounded, ExerciseMotion.squat);
const _romanianDeadlift = FitExercise('romanian_deadlift', 'exRomanianDeadliftName', 'exRomanianDeadliftCue',
    Icons.south_rounded, ExerciseMotion.squat);
const _singleLegDeadlift = FitExercise('single_leg_deadlift', 'exSingleLegDeadliftName', 'exSingleLegDeadliftCue',
    Icons.straighten_rounded, ExerciseMotion.squat);
const _curtsyLunge = FitExercise('curtsy_lunge', 'exCurtsyLungeName', 'exCurtsyLungeCue',
    Icons.swap_horiz_rounded, ExerciseMotion.lunge);
const _hipThrust = FitExercise('hip_thrust', 'exHipThrustName', 'exHipThrustCue',
    Icons.self_improvement_rounded, ExerciseMotion.squat);
const _donkeyKick = FitExercise('donkey_kick', 'exDonkeyKickName', 'exDonkeyKickCue',
    Icons.north_rounded, ExerciseMotion.core);
const _fireHydrant = FitExercise('fire_hydrant', 'exFireHydrantName', 'exFireHydrantCue',
    Icons.open_with_rounded, ExerciseMotion.core);
const _kickback = FitExercise('kickback', 'exKickbackName', 'exKickbackCue',
    Icons.south_rounded, ExerciseMotion.core);
const _frogPump = FitExercise('frog_pump', 'exFrogPumpName', 'exFrogPumpCue',
    Icons.self_improvement_rounded, ExerciseMotion.squat);
const _gluteBridgeMarch = FitExercise('glute_bridge_march', 'exGluteBridgeMarchName', 'exGluteBridgeMarchCue',
    Icons.all_inclusive_rounded, ExerciseMotion.squat);
const _clamshell = FitExercise('clamshell', 'exClamshellName', 'exClamshellCue',
    Icons.unfold_more_rounded, ExerciseMotion.core);
const _deadBug = FitExercise('dead_bug', 'exDeadBugName', 'exDeadBugCue',
    Icons.airline_seat_flat_rounded, ExerciseMotion.core);
const _hollowHold = FitExercise('hollow_hold', 'exHollowHoldName', 'exHollowHoldCue',
    Icons.timer_rounded, ExerciseMotion.core);
const _vUp = FitExercise('v_up', 'exVUpName', 'exVUpCue',
    Icons.change_history_rounded, ExerciseMotion.core);
const _toeTouch = FitExercise('toe_touch', 'exToeTouchName', 'exToeTouchCue',
    Icons.vertical_align_top_rounded, ExerciseMotion.core);
const _heelTaps = FitExercise('heel_taps', 'exHeelTapsName', 'exHeelTapsCue',
    Icons.compare_arrows_rounded, ExerciseMotion.core);
const _obliqueCrunch = FitExercise('oblique_crunch', 'exObliqueCrunchName', 'exObliqueCrunchCue',
    Icons.rotate_right_rounded, ExerciseMotion.core);
const _sideBend = FitExercise('side_bend', 'exSideBendName', 'exSideBendCue',
    Icons.swap_horiz_rounded, ExerciseMotion.core);
const _scissorKick = FitExercise('scissor_kick', 'exScissorKickName', 'exScissorKickCue',
    Icons.waves_rounded, ExerciseMotion.core);
const _plankUpDown = FitExercise('plank_up_down', 'exPlankUpDownName', 'exPlankUpDownCue',
    Icons.unfold_more_rounded, ExerciseMotion.plank);
const _wristCurl = FitExercise('wrist_curl', 'exWristCurlName', 'exWristCurlCue',
    Icons.pan_tool_rounded, ExerciseMotion.pushup);
const _reverseWristCurl = FitExercise('reverse_wrist_curl', 'exReverseWristCurlName', 'exReverseWristCurlCue',
    Icons.back_hand_rounded, ExerciseMotion.pushup);
const _deadHang = FitExercise('dead_hang', 'exDeadHangName', 'exDeadHangCue',
    Icons.vertical_align_top_rounded, ExerciseMotion.plank);
const _farmerCarry = FitExercise('farmer_carry', 'exFarmerCarryName', 'exFarmerCarryCue',
    Icons.hiking_rounded, ExerciseMotion.plank);
const _neckTilt = FitExercise('neck_tilt', 'exNeckTiltName', 'exNeckTiltCue',
    Icons.psychology_rounded, ExerciseMotion.core);
const _neckRotation = FitExercise('neck_rotation', 'exNeckRotationName', 'exNeckRotationCue',
    Icons.autorenew_rounded, ExerciseMotion.core);
const _chinTuck = FitExercise('chin_tuck', 'exChinTuckName', 'exChinTuckCue',
    Icons.south_rounded, ExerciseMotion.core);
const _sprintInPlace = FitExercise('sprint_in_place', 'exSprintInPlaceName', 'exSprintInPlaceCue',
    Icons.bolt_rounded, ExerciseMotion.jump);
const _tuckJump = FitExercise('tuck_jump', 'exTuckJumpName', 'exTuckJumpCue',
    Icons.arrow_upward_rounded, ExerciseMotion.jump);
const _plankJack = FitExercise('plank_jack', 'exPlankJackName', 'exPlankJackCue',
    Icons.horizontal_rule_rounded, ExerciseMotion.plank);
const _squatThrust = FitExercise('squat_thrust', 'exSquatThrustName', 'exSquatThrustCue',
    Icons.whatshot_rounded, ExerciseMotion.jump);
const _lateralHop = FitExercise('lateral_hop', 'exLateralHopName', 'exLateralHopCue',
    Icons.compare_arrows_rounded, ExerciseMotion.jump);
const _starJump = FitExercise('star_jump', 'exStarJumpName', 'exStarJumpCue',
    Icons.accessibility_rounded, ExerciseMotion.jump);
const _shadowBox = FitExercise('shadow_box', 'exShadowBoxName', 'exShadowBoxCue',
    Icons.sports_martial_arts_rounded, ExerciseMotion.jump);
const _bearCrawl = FitExercise('bear_crawl', 'exBearCrawlName', 'exBearCrawlCue',
    Icons.sports_gymnastics_rounded, ExerciseMotion.plank);
const _crabWalk = FitExercise('crab_walk', 'exCrabWalkName', 'exCrabWalkCue',
    Icons.sports_gymnastics_rounded, ExerciseMotion.plank);
const _jogInPlace = FitExercise('jog_in_place', 'exJogInPlaceName', 'exJogInPlaceCue',
    Icons.directions_run_rounded, ExerciseMotion.jump);
const _shoulderRoll = FitExercise('shoulder_roll', 'exShoulderRollName', 'exShoulderRollCue',
    Icons.autorenew_rounded, ExerciseMotion.jump);
const _hipCircle = FitExercise('hip_circle', 'exHipCircleName', 'exHipCircleCue',
    Icons.loop_rounded, ExerciseMotion.squat);
const _legSwing = FitExercise('leg_swing', 'exLegSwingName', 'exLegSwingCue',
    Icons.swap_horiz_rounded, ExerciseMotion.lunge);
const _torsoTwist = FitExercise('torso_twist', 'exTorsoTwistName', 'exTorsoTwistCue',
    Icons.sync_alt_rounded, ExerciseMotion.core);
const _ankleCircle = FitExercise('ankle_circle', 'exAnkleCircleName', 'exAnkleCircleCue',
    Icons.loop_rounded, ExerciseMotion.squat);
const _catCow = FitExercise('cat_cow', 'exCatCowName', 'exCatCowCue',
    Icons.all_inclusive_rounded, ExerciseMotion.core);
const _hamstringStretch = FitExercise('hamstring_stretch', 'exHamstringStretchName', 'exHamstringStretchCue',
    Icons.south_rounded, ExerciseMotion.plank);
const _quadStretch = FitExercise('quad_stretch', 'exQuadStretchName', 'exQuadStretchCue',
    Icons.north_rounded, ExerciseMotion.plank);
const _chestStretch = FitExercise('chest_stretch', 'exChestStretchName', 'exChestStretchCue',
    Icons.open_with_rounded, ExerciseMotion.plank);
const _shoulderStretch = FitExercise('shoulder_stretch', 'exShoulderStretchName', 'exShoulderStretchCue',
    Icons.front_hand_rounded, ExerciseMotion.plank);
const _hipFlexorStretch = FitExercise('hip_flexor_stretch', 'exHipFlexorStretchName', 'exHipFlexorStretchCue',
    Icons.directions_walk_rounded, ExerciseMotion.plank);
const _seatedTwist = FitExercise('seated_twist', 'exSeatedTwistName', 'exSeatedTwistCue',
    Icons.sync_alt_rounded, ExerciseMotion.plank);
const _calfStretch = FitExercise('calf_stretch', 'exCalfStretchName', 'exCalfStretchCue',
    Icons.keyboard_double_arrow_up_rounded, ExerciseMotion.plank);
const _butterflyStretch = FitExercise('butterfly_stretch', 'exButterflyStretchName', 'exButterflyStretchCue',
    Icons.spa_rounded, ExerciseMotion.plank);
const _childPose = FitExercise('child_pose', 'exChildPoseName', 'exChildPoseCue',
    Icons.spa_rounded, ExerciseMotion.plank);
const _cobraStretch = FitExercise('cobra_stretch', 'exCobraStretchName', 'exCobraStretchCue',
    Icons.north_rounded, ExerciseMotion.plank);
const _neckStretch = FitExercise('neck_stretch', 'exNeckStretchName', 'exNeckStretchCue',
    Icons.psychology_rounded, ExerciseMotion.plank);
const _downwardDog = FitExercise('downward_dog', 'exDownwardDogName', 'exDownwardDogCue',
    Icons.change_history_rounded, ExerciseMotion.plank);
const _warriorTwo = FitExercise('warrior_two', 'exWarriorTwoName', 'exWarriorTwoCue',
    Icons.accessibility_rounded, ExerciseMotion.lunge);
const _treePose = FitExercise('tree_pose', 'exTreePoseName', 'exTreePoseCue',
    Icons.spa_rounded, ExerciseMotion.plank);
const _bridgePose = FitExercise('bridge_pose', 'exBridgePoseName', 'exBridgePoseCue',
    Icons.self_improvement_rounded, ExerciseMotion.squat);
const _pilatesHundred = FitExercise('pilates_hundred', 'exPilatesHundredName', 'exPilatesHundredCue',
    Icons.waves_rounded, ExerciseMotion.core);
const _pilatesLegCircle = FitExercise('pilates_leg_circle', 'exPilatesLegCircleName', 'exPilatesLegCircleCue',
    Icons.loop_rounded, ExerciseMotion.core);
const _pilatesRollUp = FitExercise('pilates_roll_up', 'exPilatesRollUpName', 'exPilatesRollUpCue',
    Icons.unfold_more_rounded, ExerciseMotion.core);
const _pilatesSwimming = FitExercise('pilates_swimming', 'exPilatesSwimmingName', 'exPilatesSwimmingCue',
    Icons.waves_rounded, ExerciseMotion.core);

// ─── Routines ──────────────────────────────────────────────────────────────
const List<FitRoutine> kFitRoutines = [
  FitRoutine(
    'full_body',
    'fitFullBodyTitle',
    Icons.fitness_center_rounded,
    40, 15,
    sets: 2,
    gender: FitGender.both,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 8,
    exercises: [_squat, _pushup, _lunge, _plank, _mountainClimber, _gluteBridge, _jumpInPlace, _sumoSquat, _reverseLunge],
  ),
  FitRoutine(
    'cardio',
    'fitCardioTitle',
    Icons.favorite_rounded,
    30, 15,
    sets: 2,
    gender: FitGender.both,
    level: FitLevel.intermediate,
    equipment: FitEquipment.none,
    kcalPerMin: 11,
    exercises: [_jumpingJack, _highKnees, _burpee, _mountainClimber, _jumpSquat, _highKneeMarch, _skaterJump, _sideShuffle],
  ),
  FitRoutine(
    'core',
    'fitCoreTitle',
    Icons.crop_square_rounded,
    35, 10,
    sets: 2,
    gender: FitGender.both,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 7,
    exercises: [_plank, _crunches, _bicycle, _legRaise, _sidePlank, _superman, _russianTwist, _flutterKicks],
  ),
  FitRoutine(
    'warmup',
    'fitWarmupTitle',
    Icons.autorenew_rounded,
    25, 5,
    sets: 1,
    gender: FitGender.both,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 4,
    exercises: [_jogInPlace, _shoulderRoll, _armCircles, _hipCircle, _legSwing, _torsoTwist, _ankleCircle, _catCow],
  ),
  FitRoutine(
    'stretching',
    'fitStretchingTitle',
    Icons.spa_rounded,
    35, 5,
    sets: 1,
    gender: FitGender.both,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 3,
    exercises: [_hamstringStretch, _quadStretch, _chestStretch, _shoulderStretch, _hipFlexorStretch, _seatedTwist, _calfStretch, _butterflyStretch, _childPose, _cobraStretch],
  ),
  FitRoutine(
    'mobility',
    'fitMobilityTitle',
    Icons.all_inclusive_rounded,
    30, 8,
    sets: 1,
    gender: FitGender.both,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 4,
    exercises: [_catCow, _hipCircle, _ankleCircle, _torsoTwist, _birdDog, _legSwing, _shoulderRoll, _seatedTwist],
  ),
  FitRoutine(
    'home',
    'fitHomeTitle',
    Icons.crop_square_rounded,
    35, 15,
    sets: 2,
    gender: FitGender.both,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 8,
    exercises: [_squat, _kneePushup, _gluteBridge, _plank, _reverseLunge, _crunches, _superman, _calfRaise],
  ),
  FitRoutine(
    'gym',
    'fitGymTitle',
    Icons.monitor_weight_rounded,
    45, 30,
    sets: 3,
    gender: FitGender.both,
    level: FitLevel.intermediate,
    equipment: FitEquipment.barbell,
    kcalPerMin: 7,
    exercises: [_barbellSquat, _benchPressBarbell, _dumbbellRow, _overheadPress, _romanianDeadlift, _plank],
  ),
  FitRoutine(
    'hiit',
    'fitHiitTitle',
    Icons.bolt_rounded,
    25, 10,
    sets: 3,
    gender: FitGender.both,
    level: FitLevel.advanced,
    equipment: FitEquipment.none,
    kcalPerMin: 14,
    exercises: [_burpee, _sprintInPlace, _tuckJump, _plankJack, _squatThrust, _lateralHop, _starJump, _jumpSquat],
  ),
  FitRoutine(
    'chest',
    'fitChestTitle',
    Icons.fitness_center_rounded,
    35, 20,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.intermediate,
    equipment: FitEquipment.none,
    kcalPerMin: 7,
    exercises: [_pushup, _widePushup, _diamondPushup, _inclinePushup, _declinePushup, _pushupHold, _chestStretch],
  ),
  FitRoutine(
    'arms',
    'fitArmsTitle',
    Icons.fitness_center_rounded,
    35, 20,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.intermediate,
    equipment: FitEquipment.dumbbells,
    kcalPerMin: 6,
    exercises: [_bicepsCurl, _hammerCurl, _tricepsDip, _tricepsExtension, _diamondPushup, _armCircles],
  ),
  FitRoutine(
    'shoulders',
    'fitShouldersTitle',
    Icons.open_with_rounded,
    35, 20,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.intermediate,
    equipment: FitEquipment.dumbbells,
    kcalPerMin: 6,
    exercises: [_overheadPress, _lateralRaise, _frontRaise, _pikePushup, _shoulderTap, _shoulderStretch],
  ),
  FitRoutine(
    'back',
    'fitBackTitle',
    Icons.rowing_rounded,
    35, 20,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.intermediate,
    equipment: FitEquipment.none,
    kcalPerMin: 7,
    exercises: [_superman, _birdDog, _reverseSnowAngel, _australianPullup, _dumbbellRow, _goodMorning],
  ),
  FitRoutine(
    'legs',
    'fitLegsTitle',
    Icons.directions_walk_rounded,
    40, 20,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.intermediate,
    equipment: FitEquipment.none,
    kcalPerMin: 9,
    exercises: [_squat, _bulgarianSplitSquat, _stepUp, _wallSit, _calfRaise, _romanianDeadlift, _jumpSquat],
  ),
  FitRoutine(
    'glutes_men',
    'fitGlutesMenTitle',
    Icons.self_improvement_rounded,
    35, 15,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.intermediate,
    equipment: FitEquipment.none,
    kcalPerMin: 7,
    exercises: [_hipThrust, _gluteBridge, _romanianDeadlift, _reverseLunge, _donkeyKick, _singleLegDeadlift],
  ),
  FitRoutine(
    'forearms',
    'fitForearmsTitle',
    Icons.pan_tool_rounded,
    30, 15,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.beginner,
    equipment: FitEquipment.dumbbells,
    kcalPerMin: 4,
    exercises: [_wristCurl, _reverseWristCurl, _deadHang, _farmerCarry],
  ),
  FitRoutine(
    'neck',
    'fitNeckTitle',
    Icons.psychology_rounded,
    25, 10,
    sets: 2,
    gender: FitGender.male,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 3,
    exercises: [_neckTilt, _neckRotation, _chinTuck, _neckStretch],
  ),
  FitRoutine(
    'fat_burn',
    'fitFatBurnTitle',
    Icons.whatshot_rounded,
    30, 10,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.advanced,
    equipment: FitEquipment.none,
    kcalPerMin: 13,
    exercises: [_burpee, _jumpingJack, _mountainClimber, _jumpSquat, _highKnees, _squatThrust, _skaterJump, _plankJack, _shadowBox],
  ),
  FitRoutine(
    'dumbbells',
    'fitDumbbellsTitle',
    Icons.monitor_weight_rounded,
    40, 25,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.intermediate,
    equipment: FitEquipment.dumbbells,
    kcalPerMin: 7,
    exercises: [_gobletSquat, _dumbbellRow, _overheadPress, _bicepsCurl, _chestFlyDumbbell, _romanianDeadlift, _lateralRaise],
  ),
  FitRoutine(
    'barbell',
    'fitBarbellTitle',
    Icons.monitor_weight_rounded,
    45, 40,
    sets: 4,
    gender: FitGender.male,
    level: FitLevel.advanced,
    equipment: FitEquipment.barbell,
    kcalPerMin: 7,
    exercises: [_barbellSquat, _benchPressBarbell, _goodMorning, _romanianDeadlift, _overheadPress],
  ),
  FitRoutine(
    'pullup_bar',
    'fitPullupBarTitle',
    Icons.vertical_align_top_rounded,
    30, 40,
    sets: 4,
    gender: FitGender.male,
    level: FitLevel.advanced,
    equipment: FitEquipment.bar,
    kcalPerMin: 8,
    exercises: [_pullUp, _chinUp, _australianPullup, _deadHang],
  ),
  FitRoutine(
    'dips_bars',
    'fitDipsBarsTitle',
    Icons.unfold_more_rounded,
    30, 40,
    sets: 4,
    gender: FitGender.male,
    level: FitLevel.advanced,
    equipment: FitEquipment.bar,
    kcalPerMin: 8,
    exercises: [_tricepsDip, _pushupHold, _deadHang, _plank],
  ),
  FitRoutine(
    'functional',
    'fitFunctionalTitle',
    Icons.sports_gymnastics_rounded,
    35, 15,
    sets: 3,
    gender: FitGender.male,
    level: FitLevel.advanced,
    equipment: FitEquipment.none,
    kcalPerMin: 11,
    exercises: [_bearCrawl, _crabWalk, _farmerCarry, _squatThrust, _birdDog, _skaterJump, _plankUpDown],
  ),
  FitRoutine(
    'glutes_w',
    'fitGlutesWTitle',
    Icons.self_improvement_rounded,
    35, 15,
    sets: 3,
    gender: FitGender.female,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 7,
    exercises: [_gluteBridge, _hipThrust, _donkeyKick, _fireHydrant, _kickback, _frogPump, _gluteBridgeMarch, _clamshell],
  ),
  FitRoutine(
    'legs_w',
    'fitLegsWTitle',
    Icons.directions_walk_rounded,
    35, 15,
    sets: 3,
    gender: FitGender.female,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 8,
    exercises: [_sumoSquat, _curtsyLunge, _reverseLunge, _wallSit, _calfRaise, _singleLegDeadlift, _stepUp],
  ),
  FitRoutine(
    'abs_w',
    'fitAbsWTitle',
    Icons.crop_square_rounded,
    30, 12,
    sets: 3,
    gender: FitGender.female,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 7,
    exercises: [_deadBug, _crunches, _bicycle, _legRaise, _hollowHold, _vUp, _plank, _flutterKicks],
  ),
  FitRoutine(
    'waist',
    'fitWaistTitle',
    Icons.sync_alt_rounded,
    30, 12,
    sets: 3,
    gender: FitGender.female,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 7,
    exercises: [_russianTwist, _obliqueCrunch, _sideBend, _sidePlank, _heelTaps, _scissorKick, _torsoTwist],
  ),
  FitRoutine(
    'arms_w',
    'fitArmsWTitle',
    Icons.front_hand_rounded,
    30, 15,
    sets: 3,
    gender: FitGender.female,
    level: FitLevel.beginner,
    equipment: FitEquipment.dumbbells,
    kcalPerMin: 5,
    exercises: [_kneePushup, _tricepsDip, _bicepsCurl, _lateralRaise, _armCircles, _shoulderStretch],
  ),
  FitRoutine(
    'chest_w',
    'fitChestWTitle',
    Icons.fitness_center_rounded,
    30, 15,
    sets: 3,
    gender: FitGender.female,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 6,
    exercises: [_kneePushup, _inclinePushup, _widePushup, _chestFlyDumbbell, _chestStretch],
  ),
  FitRoutine(
    'pilates',
    'fitPilatesTitle',
    Icons.waves_rounded,
    35, 10,
    sets: 2,
    gender: FitGender.female,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 5,
    exercises: [_pilatesHundred, _pilatesRollUp, _pilatesLegCircle, _pilatesSwimming, _deadBug, _bridgePose, _sidePlank],
  ),
  FitRoutine(
    'yoga',
    'fitYogaTitle',
    Icons.spa_rounded,
    40, 8,
    sets: 1,
    gender: FitGender.female,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 4,
    exercises: [_downwardDog, _warriorTwo, _treePose, _bridgePose, _cobraStretch, _childPose, _catCow, _seatedTwist],
  ),
  FitRoutine(
    'weight_loss',
    'fitWeightLossTitle',
    Icons.favorite_rounded,
    30, 15,
    sets: 3,
    gender: FitGender.female,
    level: FitLevel.intermediate,
    equipment: FitEquipment.none,
    kcalPerMin: 11,
    exercises: [_jumpingJack, _squat, _mountainClimber, _highKnees, _gluteBridge, _plank, _skaterJump, _sideShuffle],
  ),
  FitRoutine(
    'posture',
    'fitPostureTitle',
    Icons.straighten_rounded,
    30, 10,
    sets: 2,
    gender: FitGender.female,
    level: FitLevel.beginner,
    equipment: FitEquipment.none,
    kcalPerMin: 4,
    exercises: [_chinTuck, _reverseSnowAngel, _birdDog, _superman, _chestStretch, _catCow, _shoulderRoll],
  ),
];
